name: "Deploy Action"
description: "Deploys the SAM template"

runs:
  steps:
    - uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup SAM CLI
      uses: aws-actions/setup-sam@v2

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: SAM Build
      run: sam build
    
    - name: SAM Deploy
      run: sam deploy
              --s3-prefix ${{ secrets.STACK_NAME }}
              --s3-bucket ${{ secrets.S3_DEPLOYMENT_BUCKET }}
              --capabilities CAPABILITY_IAM
              --stack-name ${{ secrets.STACK_NAME }}
              --no-confirm-changeset
              --no-fail-on-empty-changeset
              --parameter-overrides
                  'ParameterKey=StageName,ParameterValue=${{ secrets.STAGE_NAME }}
                  ParameterKey=TableName,ParameterValue=${{ secrets.DYNAMO_TABLE_NAME }}
                  ParameterKey=TopicName,ParameterValue=${{ secrets.TOPIC_NAME }}
                  ParameterKey=JwtSecretKey,ParameterValue=${{ secrets.JWT_SECRET_KEY }}'












