name: Triple-T Development Backend Deployment

on:
  push:
    # paths: 
    #   - 'Source'
    branches: 
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: ./deploy-action.yaml












