name: Triple-T Development Backend Deployment

on:
  push:
    # paths: 
    #   - 'Source'
    branches: 
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-stack-name: ${{ secrets.STACK_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
          sam-bucket: ${{ secrets.S3_DEPLOYMENT_BUCKET }}
          stage-name: ${{ secrets }}
          dynamo-db-table-name: ${{ secrets.DYNAMO_TABLE_NAME }}
          sns-topic-name: ${{ secrets.TOPIC_NAME }}
          jwt-secret-key: ${{ secrets.JWT_SECRET_KEY }}
          aws-iam-capability: CAPABILITY_IAM












