name: Triple-T Production Backend Deployment

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v2
      - uses: ./deploy-action.yaml












